# Generated by Django 3.0.5 on 2020-04-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
